apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: pacman-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PacmanGame is the Schema for the PacmanGames API
      displayName: Pacman Game
      kind: PacmanGame
      name: pacmangames.apps.rha.lab
      version: v1beta1
  description: Deploys and Manages instances of Pacman Arcade Game
  displayName: Pacman Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - pacman
  - arcade
  - games
  links:
  - name: Pacman Operator
    url: https://pacman-operator.domain
  maturity: alpha
  provider:
    name: RHA
    url: linuxera.org
  version: 0.0.0
