apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman
subjects:
- kind: ServiceAccount 
  name: pacman
  namespace: pacman-game-ui
roleRef:
  kind: ClusterRole
  name: pacman 
  apiGroup: rbac.authorization.k8s.io