# permissions for end users to edit pacmangames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacmangame-editor-role
rules:
- apiGroups:
  - apps.rha.lab
  resources:
  - pacmangames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.rha.lab
  resources:
  - pacmangames/status
  verbs:
  - get
