# permissions for end users to view pacmangames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacmangame-viewer-role
rules:
- apiGroups:
  - apps.rha.lab
  resources:
  - pacmangames
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.rha.lab
  resources:
  - pacmangames/status
  verbs:
  - get
